---
title:        A Cosmology Group
longtitle:    A Cosmology Group - Observations, inferences and the fading confidence in Î›CDM cosmology
remote_theme: sighingnow/jekyll-gitbook
toc:
  enabled: true
  h_min: 1
  h_max: 3
plugins:
  - jekyll-remote-theme
---
